application: mapreduce-demo
version: 1
runtime: python39
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

- url: /mapreduce/pipeline(/.*)?
  script: main.py

- url: .*
  script: main.py
  login: required

- url: /mapreduce/pipeline/images
  static_dir: pipeline/ui/images
